version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8094}:8094"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      WS_HOST: localhost
      WS_PORT: 8080
      RESET_TIME: 0 # Время в секундах до автоматического отжатия, 0 - автоматически не отжимаются
    command: npm start