services:
  app-dev:
    build:
      context: .
      target: dev
    ports:
      - "8094:8094"
    environment:
      NODE_ENV: production
      WS_HOST: ${WS_HOST}
      WS_PORT: ${WS_PORT}
      RESET_TIME: ${RESET_TIME}
    volumes:
      - .:/app
      - /app/node_modules

  app-prod:
    build:
      context: .
      target: prod
      args:
        WS_HOST: ${WS_HOST}
        WS_PORT: ${WS_PORT}
        RESET_TIME: ${RESET_TIME}
    ports:
      - "8094:8094"
    environment:
      NODE_ENV: production
      WS_HOST: ${WS_HOST}
      WS_PORT: ${WS_PORT}
      RESET_TIME: ${RESET_TIME}